[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = ['postgresql']

[phases.install]
cmds = ['cd backend && npm ci --omit=dev']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'cd backend && npm start'
