[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd backend && npm install --production']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'cd backend && npm start'
